[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
opbnb_testnet = "https://opbnb-testnet-rpc.bnbchain.org"

[fmt]
line_length=120
